### ISSUE TITLE
THIS IS NOT AN ISSUE

### ISSUE THREAD

**Issue by AryanMangale** [erictleung/dotfiles#25]
Hello @erictleung ,
This repo is very similar to what I am trying to achieve in my [Anew](https://github.com/aryanmangale/Anew) repository.
I would be glad if you gave feedback in the future.

**Comment by erictleung** [comment]
Thanks for your comments. This repository is more of a personal configuration that isn't meant to be generalizable for others. It is just meant to help others who want it. Thanks again for sharing your project! Good luck!
